packages:
    - 'shared/*'
    - 'app/*'

catalog:
    react: ^19.0.0
    react-dom: ^19.0.0
    styled-components: ^6.1.15
    vite: ^6.2.1
    vite-plugin-svgr: ^4.3.0
    prettier: ^3.5.3
    typescript: ^5.8.2
    eslint: ^9.21.0
    '@eslint/js': ^9.21.0
    eslint-plugin-react: ^7.37.4
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.19
    eslint-plugin-prettier: ^5.2.3
    eslint-config-prettier: ^10.1.0
    typescript-eslint: ^8.26.0
    '@types/react': ^19.0.10
    '@types/react-dom': ^19.0.4
    '@vitejs/plugin-react': ^4.3.4
    globals: ^15.15.0
    husky: ^9.1.7
    lint-staged: ^15.4.3
    vite-tsconfig-paths: ^5.1.4
    jotai: ^2.12.1
    react-router: ^7.3.0
    vite-plugin-dts: ^4.5.3
    i18next: ^24.2.2
    react-i18next: ^15.4.0
